# CONFIG_BSP_USING_GPIO is not set
CONFIG_BSP_UART1_TX_USING_DMA=y
CONFIG_BSP_USING_UART2=y
CONFIG_BSP_UART2_RX_USING_DMA=y
CONFIG_BSP_UART2_TX_USING_DMA=y
# CONFIG_BSP_USING_SPI is not set
# CONFIG_BSP_USING_I2C is not set
# CONFIG_BSP_USING_TIM is not set
# CONFIG_BSP_USING_PWM is not set
# CONFIG_BSP_USING_ADC is not set
# CONFIG_BSP_USING_MPI is not set
# CONFIG_BSP_USING_EXT_DMA is not set
# CONFIG_BSP_USING_HW_AES is not set
# CONFIG_BSP_USING_ONCHIP_RTC is not set
# CONFIG_BSP_USING_EPIC is not set
# CONFIG_BSP_USING_PINMUX is not set
# CONFIG_BSP_ENABLE_AUD_PRC is not set
# CONFIG_BSP_ENABLE_AUD_CODEC is not set
CONFIG_BSP_NOT_DISABLE_UNUSED_MODULE=y
# CONFIG_BSP_USING_LCD is not set
# CONFIG_BSP_USING_KEY1 is not set
# CONFIG_RT_USING_CPLUSPLUS is not set
CONFIG_FINSH_THREAD_NAME="cxk"
# CONFIG_RT_USING_DFS is not set
CONFIG_RT_SERIAL_RB_BUFSZ=256
CONFIG_RT_SERIAL_DEFAULT_BAUDRATE=115200
CONFIG_RT_USING_ULOG=y
